server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.21.101.44:3306/osc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: fushenqi
  redis:
    port: 6379
    host: 10.21.101.44
    database: 2
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    password: 'fushenqi123'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
mybatis-plus:
  type-aliases-package: cn.osc.entity
  mapper-locations: cn/osd/mapper/*.xml
